export const ActionTypes = {
    SET_CURRENT_USER: "SET_CURRENT_USER",

    REGISTER_INITIATE: "REGISTER_INITIATE",
    REGISTER_ERROR: "REGISTER_ERROR",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",

    LOGIN_INITIATE: "LOGIN_INITIATE",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",

    GOOGLE_AUTH: "GOOGLE_AUTH",
    
    MOBILE_INITIATE: "MOBILE_INITIATE",
    MOBILE_SUCCESS: "MOBILE_SUCCESS",
    MOBILE_ERROR: "MOBILE_ERROR",

    FORGOT_PASSWORD_INITIATE: "FORGOT_PASSWORD_INITIATE",
    FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_ERROR: "FORGOT_PASSWORD_ERROR",

    REMOVE_ERROR: "REMOVE_ERROR",
    
    HANDLE_MODAL: "HANDLE_MODAL"
}